Integrate solidity-coverage
uniqxio/market-contracts pull request #3
Opened 2018-10-16 09:30 UTC by scoriiu

2018-10-18 16:01 UTC, imcu requested changes
There are a few comments. Looks good otherwise!

2018-10-18 16:01 UTC, imcu commented on change.sh
> +name="./allFiredEvents"
We don't need this file committed at all.

2018-10-18 16:01 UTC, imcu commented on test/helpers/expectEvent.js
> +	return true; //_.isEqual(args1, args2);
Do we want to do this ?

2018-10-18 16:01 UTC, imcu commented on test/helpers/expectEvent.js
> +	return true;
Do we want to do this ?

2018-10-18 16:01 UTC, imcu commented on test/helpers/expectEvent.js
> +	return true;
Do we want to do this ?

2018-10-18 16:01 UTC, imcu commented on test/market-uniqx-auction/01-market-uniqx-auction.test.js
> +	it('should be able to register the tokens tokens', async() => {
Typo: `tokens tokens`

2018-10-18 16:01 UTC, imcu commented on test/market-uniqx-auction/01-market-uniqx-auction.test.js
> +		await market.disableOrders(
I think the correct call here should be `disableTokenOrders`. What you called is the same as the global one.

2018-10-18 16:39 UTC, scoriiu commented on test/market-uniqx-auction/01-market-uniqx-auction.test.js
> +		await market.disableOrders(
Right. This function, if written correctly, is a duplicate of the the function on line 169. Therefore should be removed.

2018-10-18 16:41 UTC, scoriiu commented on test/helpers/expectEvent.js
> +	return true; //_.isEqual(args1, args2);
ups :D

2018-10-18 16:41 UTC, scoriiu commented on change.sh
> +name="./allFiredEvents"
Right

2018-10-18 17:00 UTC, scoriiu commented on test/helpers/expectEvent.js
> +	return true; //_.isEqual(args1, args2);
fixed

2018-10-18 17:31 UTC, merged

2018-10-21 14:24 UTC, imcu commented on test/market-uniqx-auction/01-market-uniqx-auction.test.js
> +		await market.disableOrders(
Yes, but you had a parameter as the token address. Did you fix this in the last commit?